### ISSUE TITLE
create fizzbuzz

### ISSUE THREAD

**Issue by wtmo-dev** [KGK-Proj/KGK_firstProj#1]
## Description
we will create fizzbuzz.py

## Tasks
- [ ] 1. create feature of fizz
- [ ] 2. create feature of buzz
- [ ] 3. create feature of fizzbuzz
- [ ] 4. refactor the fizzbuzz

## References
[ref.1](link)
