### ISSUE TITLE
create pig dice game skeleton

### ISSUE THREAD

**Issue by wtmo-dev** [KGK-Proj/KGK_firstProj#2]
## Description
make skeleton of pig dice game

## Tasks
- [ ] 1. make pig dice game's class
- [ ] 2. make pig dice game definition of input
- [ ] 3. make pig dice game definition of output

## References
[ref.1](https://pythonscholar.com/python-projects/pig-game-in-python/)
