### ISSUE TITLE
create pig dice game state

### ISSUE THREAD

**Issue by wtmo-dev** [KGK-Proj/KGK_firstProj#3]
## Description
add option of pig dice game

## Tasks
- [ ] 1. make next players turn when the dice comes 1
- [ ] 2. make option for the player select stay or keep roll
- [ ] 3. make end point when someone reach 100 point

## References
[ref.1](https://pythonscholar.com/python-projects/pig-game-in-python/)
